test: fix it

diff --git a/.github/workflows/it.yml b/.github/workflows/it.yml
--- a/.github/workflows/it.yml
+++ b/.github/workflows/it.yml
@@ -57,31 +57,32 @@ jobs:
           sh ./initAWS.sh bpartners ${{ secrets.BPARTNERS_AWS_ACCESS_KEY_ID }} ${{ secrets.BPARTNERS_AWS_SECRET_ACCESS_KEY }} ${{ secrets.BPARTNERS_AWS_REGION }}
           sh ./initNpmrc.sh bpartners bpartners-store npm-bpartners-app 688605879718
       - run: npm install --legacy-peer-deps
-      # - run: |
-      #     echo REACT_APP_AWS_REGION=${{ env.AWS_REGION }} > .env
-      #     echo REACT_APP_USERPOOL_ID=${{ env.PROD_USERPOOL_ID }} >> .env
-      #     echo REACT_APP_WEBCLIENT_ID=${{ env.PROD_WEBCLIENT_ID }} >> .env
-      #     echo REACT_APP_OAUTH_DOMAIN=${{ env.PROD_OAUTH_DOMAIN }} >> .env
-      #     echo REACT_APP_REDIRECT_SUCCESS=${{ env.PROD_REDIRECT_SUCCESS }} >> .env
-      #     echo REACT_APP_BPARTNERS_API_URL=https://api.prod.bpartners.app >> .env
-      #     echo REACT_APP_IT_USERNAME=${{ secrets.IT_USERNAME }} >> .env
-      #     echo REACT_APP_IT_PASSWORD='${{ secrets.IT_PASSWORD }}' >> .env
-      #     echo REACT_APP_PROD_URL='${{ secrets.REACT_APP_PROD_URL }}' >> .env
-      #     echo REACT_APP_IT_ONBOARD_USERNAME=${{ secrets.REACT_APP_IT_ONBOARD_USERNAME }}  >> .env
-      #     echo REACT_APP_IT_ONBOARD_PASSWORD_1=${{ secrets.REACT_APP_IT_ONBOARD_PASSWORD_1 }}  >> .env
-      #     echo REACT_APP_IT_ONBOARD_PHONE_NUMBER=${{ secrets.REACT_APP_IT_ONBOARD_PHONE_NUMBER }} >> .env
-      #     max_retries=5
-      #     attempt=1
-      #     until npm run it
-      #     do
-      #       if [ $attempt -ge $max_retries ]; then
-      #         echo "Tests failed after $attempt attempts."
-      #         exit 1
-      #       fi
-      #       echo "Test failed. Retrying attempt $((attempt+1)) of $max_retries..."
-      #       attempt=$((attempt+1))
-      #       sleep 5
-      #     done
+      - run: |
+          echo REACT_APP_AWS_REGION=${{ env.AWS_REGION }} > .env
+          echo REACT_APP_USERPOOL_ID=${{ env.PROD_USERPOOL_ID }} >> .env
+          echo REACT_APP_WEBCLIENT_ID=${{ env.PROD_WEBCLIENT_ID }} >> .env
+          echo REACT_APP_OAUTH_DOMAIN=${{ env.PROD_OAUTH_DOMAIN }} >> .env
+          echo REACT_APP_REDIRECT_SUCCESS=${{ env.PROD_REDIRECT_SUCCESS }} >> .env
+          echo REACT_APP_BPARTNERS_API_URL=https://api.prod.bpartners.app >> .env
+          echo REACT_APP_IT_USERNAME=${{ secrets.IT_USERNAME }} >> .env
+          echo REACT_APP_IT_PASSWORD='${{ secrets.IT_PASSWORD }}' >> .env
+          echo REACT_APP_PROD_URL='${{ secrets.REACT_APP_PROD_URL }}' >> .env
+          echo REACT_APP_IT_ONBOARD_USERNAME=${{ secrets.REACT_APP_IT_ONBOARD_USERNAME }}  >> .env
+          echo REACT_APP_IT_ONBOARD_PASSWORD_1=${{ secrets.REACT_APP_IT_ONBOARD_PASSWORD_1 }}  >> .env
+          echo REACT_APP_IT_ONBOARD_PHONE_NUMBER=${{ secrets.REACT_APP_IT_ONBOARD_PHONE_NUMBER }} >> .env
+          max_retries=5
+          attempt=1
+
+          until npm run it
+          do
+            if [ $attempt -ge $max_retries ]; then
+              echo "Tests failed after $attempt attempts."
+              exit 1
+            fi
+            echo "Test failed. Retrying attempt $((attempt+1)) of $max_retries..."
+            attempt=$((attempt+1))
+            sleep 5
+          done
 
         id: it-test
       - name: Remove last user
